### ISSUE TITLE
Fix footer bug on Website

### ISSUE THREAD

**Issue by realrobertdouglas** [texashighfrequency/atlas#7]
The footer should attach to page not be fixed in view (detail of bug can be found in Telegram)

**Comment by coip** [comment]
Wondering how wrong this sort of approach might be: https://stackoverflow.com/questions/10592411/disable-scrolling-in-all-mobile-devices

**Comment by coip** [comment]
Believe this is g2g, kindly reopen if the bug persists on your device. have tested on desktop and iPhone XS
